server:
  port: 8081

spring:
  application:
    name: qnl
  data:
    mongodb:
      host: localhost
      port: 27017
      database: qnl

qnl:
  dataParser:
      classTag:
        round: jornadai
        result: resultatr_in
        local: localrr
        visitor: visitantrr
        localRes: marcalocalrr
        visitorRes: marcavisitantrr
