server:
  port: 8081

spring:
  application:
    name: qnl
  data:
    mongodb:
      host: localhost
      port: 27017
      database: qnl

qnl:
  dataParser:
      classTag:
        round: jornadai
        roundPrefix: ij
        result: resultatr_in
        local: localrr
        visitor: visitantrr
        localRes: marcalocalrr
        visitorRes: marcavisitantrr
      notDisputed: "-"
  points:
    win: 3
    draw: 1
    lose: 0
  defaultMaxIterations: 10
