server:
  port: 8081

spring:
  application:
    name: qnl
  data:
    mongodb:
      database: qnl
      host: localhost
      port: 27017

qnl:
  dataParser:
      classTag:
        local: localrr
        localRes: marcalocalrr
        result: resultatr_in
        round: jornadai
        roundPrefix: ij
        visitor: visitantrr
        visitorRes: marcavisitantrr
      notDisputed: "-"
  defaultMaxIterations: 10
  points:
    draw: 1
    lose: 0
    win: 3
  statistics:
    minDataQuantityToBeValid: 10
    minIncrement: 0.05
    # TEST | ALL
    multiple: TEST
#    percentageControl: 0.1
    percentageControl: 0.95
    weight:
      points: 0.1
      position: 0.1
      sequence: 0.1
      pointsPosition: 0.1
      pointsSequence: 0.1
      positionSequence: 0.1
      pointsPositionSequence: 0.4
